services:
  auth-service:
    build: ./authService
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET = ${JWT_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - AUTH_DB_URL=${AUTH_DB_URL}
      - PROFILE_DB_URL=${PROFILE_DB_URL}
      - RABBITMQ_EXCHANGE_USER_REGISTERED=${RABBITMQ_EXCHANGE_USER_REGISTERED}
      - RABBITMQ_QUEUE_USER_REGISTERED=${RABBITMQ_QUEUE_USER_REGISTERED}
      - RABBITMQ_ROUTING_KEY_USER_REGISTERED=${RABBITMQ_ROUTING_KEY_USER_REGISTERED}

    command: mvn clean install
    depends_on:
      - auth-db
      - rabbitmq

  profile-service:
    build: ./profileService
    ports:
      - "8081:8081"
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PROFILE_DB_URL=${PROFILE_DB_URL}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_EXCHANGE_USER_REGISTERED=${RABBITMQ_EXCHANGE_USER_REGISTERED}
      - RABBITMQ_QUEUE_USER_REGISTERED=${RABBITMQ_QUEUE_USER_REGISTERED}
      - RABBITMQ_ROUTING_KEY_USER_REGISTERED=${RABBITMQ_ROUTING_KEY_USER_REGISTERED}

    command: mvn clean install
    depends_on:
      - profile-db
      - rabbitmq

  task-service:
    build: ./taskService
    ports:
      - "8082:8082"
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TASK_DB_URL=${TASK_DB_URL}

    command: mvn clean install
    depends_on:
      - task-db

  auth-db:
    image: postgres:16
    ports:
      - "54321:5432"
    env_file: .env
    environment:
      - POSTGRES_DB=todo_auth
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  profile-db:
    image: postgres:16
    ports:
      - "54322:5432"
    env_file: .env
    environment:
      - POSTGRES_DB=todo_profile
    volumes:
      - profile_db_data:/var/lib/postgresql/data

  task-db:
    image: postgres:16
    ports:
      - "54323:5432"
    env_file: .env
    environment:
      - POSTGRES_DB=todo_task
    volumes:
      - task_db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}

volumes:
  auth_db_data:
  profile_db_data:
  task_db_data:
